main_path: /Users/rmaiwald/Levante/Paris/
data_path: ./Input/
figures_path: ./Figures/
gramm_gral_conf_path: /Users/rmaiwald/Paris/GRAMM-GRAL-data/
output_path: ./Output/
# Model input
temporal_profiles_path: ./Input/Fluxes/temporal_profiles.nc
source_groups_path: ./Input/Fluxes/source_groups.nc
# Measurements
meteo_path: ./Input/6_measurements/6_1_meteo/
# Model output
gramm_meteo_path: ./Output/gramm_05_paper/data_at_stations/
gral_meteo_path: ./Output/gral_16_paper/data_at_stations/
gral_co2_path: ./Output/gral_16_paper/data_at_stations/
domain:
  crs: EPSG:2154
  gral:
    conf_path: ./GRAMM-GRAL-data/gral_16_paper/
    bbox:
      x0: 640485.
      y0: 6854565.
      x1: 659705.
      y1: 6869765.
    dx: 10.
    dy: 10.
  gramm:
    conf_path: ./GRAMM-GRAL-data/gramm_05_paper/
    bbox:
      x0: 630750.
      y0: 6846850.
      x1: 669350.
      y1: 6877450.
    dx: 100.
    dy: 100.
    nz: 22
    z0: 10.0
    vert_stretching: 1.2
fluxes:
  nx_areas: 9
  ny_areas: 7
matching:
  stations:
    LONGCHAMP: gramm
    PARIS-MONTSOURIS: gral
    TOUR EIFFEL: gral
    LFPB: gramm
    LFPN: gramm
    LFPO: gramm
    LFPV: gramm
    Cité des Sciences: gral
    Meudon: gral
    Romainville: gral
  time_start: 2023-01-01 00:00
  time_end: 2023-12-31 23:00
