data_path: /Users/rmaiwald/Levante/Paris/Input/
figure_path: /Users/rmaiwald/Levante/Paris/Figures/
gramm_gral_conf_path: /Users/rmaiwald/Paris/GRAMM-GRAL-data/conf/
gramm_meteo_path: /Users/rmaiwald/Levante/Paris/Output/gramm_0/data_at_stations/
gral_meteo_path: /Users/rmaiwald/Levante/Paris/Output/gral_11/data_at_stations/
gral_co2_path: /Users/rmaiwald/Levante/Paris/Output/gral_13_origins_earth/data_at_stations/
domain:
  crs: EPSG:2154
  gral:
    bbox:
      x0: 640490.
      y0: 6854570.
      x1: 659700.
      y1: 6869760.
    dx: 10.
    dy: 10.
  gramm:
    conf_path: /Users/rmaiwald/Levante/Paris/GRAMM-GRAL-data/gramm_05_paper/
    bbox:
      x0: 630750.
      y0: 6846850.
      x1: 669350.
      y1: 6877450.
    dx: 100.
    dy: 100.
    nz: 22
    z0: 10.0
    vert_stretching: 1.2
